name: unix_disk_space
description: Get free disk space info from df, Works on Unix-based systems.
version: 0.1.0
homepage: https://github.com/xtyxtyx/unix_disk_space

environment:
  sdk: '>=2.5.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
